# Generated by Django 2.1.3 on 2018-12-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='twitter',
            field=models.BooleanField(default=False),
        ),
    ]
