# Generated by Django 2.1.2 on 2019-01-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181206_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appId', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.BooleanField(default=False),
        ),
    ]
