# Generated by Django 2.1.2 on 2019-01-08 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190107_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Google',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appId', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Google Analitycs identyfikator śledzenia',
                'verbose_name_plural': 'Google Analitycs identyfikator śledzenia',
            },
        ),
        migrations.AlterModelOptions(
            name='facebook',
            options={'verbose_name': 'Facebook identyfikator aplikacji', 'verbose_name_plural': 'Facebook identyfikator aplikacji'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posty'},
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.BooleanField(default=False, verbose_name='Komentarze'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='post',
            name='facebook',
            field=models.BooleanField(default=False, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data opublikowania'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='post',
            name='twitter',
            field=models.BooleanField(default=False, verbose_name='Twitter'),
        ),
    ]
