# Generated by Django 2.1.2 on 2019-01-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190108_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Blog', max_length=200, verbose_name='Nazwa bloga')),
                ('post_color', models.CharField(default='#007bff', max_length=200, verbose_name='Kolor tytułu postów')),
                ('navbar_color', models.CharField(default='#007bff', max_length=200, verbose_name='Kolor paska nawigacji')),
                ('navbar_text_color', models.CharField(default='#ffffff', max_length=200, verbose_name='Kolor tekstu paska nawigacji')),
                ('about_enabled', models.BooleanField(default=True, verbose_name='Strona "o autorze" widoczna')),
                ('contact_enabled', models.CharField(max_length=200, verbose_name='Strona "kontakt" widoczna')),
                ('newsletter_enabled', models.CharField(max_length=200, verbose_name='Strona "newsletter" widoczna')),
            ],
            options={
                'verbose_name': 'Ustawienia',
                'verbose_name_plural': 'Ustawienia',
            },
        ),
        migrations.AlterField(
            model_name='facebook',
            name='appId',
            field=models.CharField(max_length=200, verbose_name='identyfikator aplikacji'),
        ),
        migrations.AlterField(
            model_name='google',
            name='appId',
            field=models.CharField(max_length=200, verbose_name='identyfikator śledzenia'),
        ),
    ]
