# Generated by Django 2.1.2 on 2019-01-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190108_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='contact_enabled',
            field=models.BooleanField(default=True, verbose_name='Strona "kontakt" widoczna'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='newsletter_enabled',
            field=models.BooleanField(default=True, verbose_name='Strona "newsletter" widoczna'),
        ),
    ]
