# Generated by Django 2.1.2 on 2019-01-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190108_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='custom_css',
            field=models.CharField(default='', max_length=10000, verbose_name='Własny CSS (opcja dla zaawansowanych)'),
        ),
    ]
