# Generated by Django 2.1.2 on 2019-01-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.TextField(default='', max_length=2000, verbose_name='Wiadomość'),
        ),
    ]
