# Generated by Django 2.1.2 on 2019-01-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_contact_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_date',
        ),
        migrations.AddField(
            model_name='contact',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Przeczytana'),
        ),
    ]
