# Generated by Django 2.1.2 on 2019-01-08 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190108_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data wysłania'),
        ),
    ]
