# Generated by Django 2.1.2 on 2019-01-08 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190108_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=200, verbose_name='Email')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data zapisnia')),
                ('confimed', models.BooleanField(default=False, verbose_name='potwierdzono')),
                ('code', models.CharField(default='', max_length=50, verbose_name='Kod potwierdzający')),
            ],
            options={
                'verbose_name': 'Zapisany do newslettera',
                'verbose_name_plural': 'Zapisani do newslettera',
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data wysłania'),
        ),
    ]
