# Generated by Django 2.1.2 on 2019-01-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190108_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='custom_css',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Własny CSS (opcja dla zaawansowanych)'),
        ),
    ]
