# Generated by Django 2.1.2 on 2019-01-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190108_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(max_length=200, verbose_name='Użytkownik'),
        ),
    ]
