# Generated by Django 2.1.2 on 2019-01-08 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190108_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='confimed',
            new_name='confirmed',
        ),
    ]
