# Generated by Django 2.1.5 on 2019-01-08 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20190108_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Newsletter', 'verbose_name_plural': 'Newsletter'},
        ),
        migrations.AlterField(
            model_name='message',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data wysłania'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=20000, verbose_name='Zawartość'),
        ),
    ]
