# Generated by Django 2.1.5 on 2019-01-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20190108_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='about_enabled',
            field=models.BooleanField(default=False, verbose_name='Strona "o autorze" widoczna'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='contact_enabled',
            field=models.BooleanField(default=False, verbose_name='Strona "kontakt" widoczna'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='newsletter_enabled',
            field=models.BooleanField(default=False, verbose_name='Strona "newsletter" widoczna'),
        ),
    ]
